version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: algotrading_monitor
      POSTGRES_USER: algotrading
      POSTGRES_PASSWORD: algotrading_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  git_cloning_service:
    build:
      context: ./services/git_cloning_service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=git-cloning-service
      - DB_NAME=algotrading_monitor
      - DB_USER=algotrading
      - DB_PASSWORD=algotrading_pass
      - DB_HOST=postgres
      - DB_PORT=5432
      - GIT_CLONE_DIR=/app/cloned_repos
      - GIT_TIMEOUT=300
    volumes:
      - ./services/git_cloning_service:/app
      - git_repos:/app/cloned_repos

  file_selection_service:
    build:
      context: ./services/file_selection_service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=file-selection-service
      - DB_NAME=algotrading_monitor
      - DB_USER=algotrading
      - DB_PASSWORD=algotrading_pass
      - DB_HOST=postgres
      - DB_PORT=5432
      - FILE_SELECTION_BATCH_SIZE=100
    volumes:
      - ./services/file_selection_service:/app
      - git_repos:/app/cloned_repos:ro

  rag_loading_service:
    build:
      context: ./services/rag_loading_service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=rag-loading-service
      - DB_NAME=algotrading_monitor
      - DB_USER=algotrading
      - DB_PASSWORD=algotrading_pass
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./services/rag_loading_service:/app
      - git_repos:/app/cloned_repos:ro

  ai_analysis_service:
    build:
      context: ./services/ai_analysis_service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=ai-analysis-service
      - DB_NAME=algotrading_monitor
      - DB_USER=algotrading
      - DB_PASSWORD=algotrading_pass
      - DB_HOST=postgres
      - DB_PORT=5432
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODELS=${OPENROUTER_MODELS}
      - ANALYSIS_TIMEOUT=600
    volumes:
      - ./services/ai_analysis_service:/app
      - git_repos:/app/cloned_repos:ro

volumes:
  kafka_data:
  postgres_data:
  git_repos: